// <auto-generated />
namespace wwwdrivesafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class android_user_and_membership_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(android_user_and_membership_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201504300808076_android_user_and_membership_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
