// <auto-generated />
namespace wwwdrivesafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class fixforAndroidUserInfotable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixforAndroidUserInfotable));
        
        string IMigrationMetadata.Id
        {
            get { return "201504140221313_fix-for-AndroidUserInfo-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
