// <auto-generated />
namespace wwwdrivesafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_ID_Android : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ID_Android));
        
        string IMigrationMetadata.Id
        {
            get { return "201503130202533_add_ID_Android"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
